### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by sfcgeorge** [porras/tlcr#4] opened 2016-01-02 18:58 UTC
Installed with brew by following instructions.

```
#~> tlcr cd
Fetching index...
unexpected end of http response (Exception)
[4482230683] *raise<String>:NoReturn +139
[4482293217] *HTTP::Client#exec<HTTP::Client, String, String, Nil, Nil>:HTTP::Response +8385
[4482269455] *Tlcr::Client#index<Tlcr::Client>:Tlcr::Index +1519
[4482211524] __crystal_main +23748
[4482253963] main +43
#~> tlcr -u
Index out of bounds (IndexError)
[4373581278] ~fun_literal_42 +190
[4373461895] __crystal_main +22919
[4373505163] main +43
```

**Comment by porras** [comment] 2016-01-03 20:04
Hi!

Thanks for trying `tlcr` and reporting those two issues (which are independent).

What's the context of the first failure? Is it permanent or temporal? I'd associate it to a network problem (which could admitedly be reported in a much nicer way) but can't reproduce it. I'm creating a new issue for it.

The second one is fixed by #5.

**Closed as completed** 2016-01-03 20:07 UTC
